/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'actiontask': RouteRecordInfo<'actiontask', '/actiontask', Record<never, never>, Record<never, never>>,
    'credit-application': RouteRecordInfo<'credit-application', '/credit-application', Record<never, never>, Record<never, never>>,
    'credit-application-approval-id': RouteRecordInfo<'credit-application-approval-id', '/credit-application/approval/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'credit-application-line-application': RouteRecordInfo<'credit-application-line-application', '/credit-application/line-application', Record<never, never>, Record<never, never>>,
    'credit-application-list': RouteRecordInfo<'credit-application-list', '/credit-application/list', Record<never, never>, Record<never, never>>,
    'credit-application-request': RouteRecordInfo<'credit-application-request', '/credit-application/request', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'dashboardplan': RouteRecordInfo<'dashboardplan', '/dashboardplan', Record<never, never>, Record<never, never>>,
    'factoring-request': RouteRecordInfo<'factoring-request', '/factoring-request', Record<never, never>, Record<never, never>>,
    'factoring-request-approval-id': RouteRecordInfo<'factoring-request-approval-id', '/factoring-request/approval/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'index copy': RouteRecordInfo<'index copy', '/index copy', Record<never, never>, Record<never, never>>,
    'kanban': RouteRecordInfo<'kanban', '/kanban', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'logout': RouteRecordInfo<'logout', '/logout', Record<never, never>, Record<never, never>>,
    'main': RouteRecordInfo<'main', '/main', Record<never, never>, Record<never, never>>,
    'po-list': RouteRecordInfo<'po-list', '/po-list', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'registration-management-list': RouteRecordInfo<'registration-management-list', '/registration-management/list', Record<never, never>, Record<never, never>>,
    'registration-management-view-id': RouteRecordInfo<'registration-management-view-id', '/registration-management/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'tasklist': RouteRecordInfo<'tasklist', '/tasklist', Record<never, never>, Record<never, never>>,
    'tasklist2': RouteRecordInfo<'tasklist2', '/tasklist2', Record<never, never>, Record<never, never>>,
    'verify-email': RouteRecordInfo<'verify-email', '/verify-email', Record<never, never>, Record<never, never>>,
  }
}
